//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrenador
    {
        public Entrenador()
        {
            this.Bitácora = new HashSet<Bitácora>();
            this.Entrenador_Pokemon = new HashSet<Entrenador_Pokemon>();
            this.Entrenador_Pokemon_Movimiento = new HashSet<Entrenador_Pokemon_Movimiento>();
            this.Redes_Sociales_E = new HashSet<Redes_Sociales_E>();
        }
    
        public string Identificador_E { get; set; }
        public string Nombre_E { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public int Núm_Teléfono { get; set; }
        public string Provincia { get; set; }
        public string Cantón { get; set; }
        public string Distrito { get; set; }
        public string Otras_señas { get; set; }
        public string Correo_Electrónico { get; set; }
        public string Ubicación { get; set; }
        public string Sitio_Web { get; set; }
        public string Nombre_Usuario { get; set; }
    
        public virtual ICollection<Bitácora> Bitácora { get; set; }
        public virtual ICollection<Entrenador_Pokemon> Entrenador_Pokemon { get; set; }
        public virtual ICollection<Entrenador_Pokemon_Movimiento> Entrenador_Pokemon_Movimiento { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Redes_Sociales_E> Redes_Sociales_E { get; set; }
    }
}
