//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class test1Entities : DbContext
    {
        public test1Entities()
            : base("name=test1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bitácora> Bitácora { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Entrenador> Entrenadors { get; set; }
        public DbSet<Entrenador_Pokemon> Entrenador_Pokemon { get; set; }
        public DbSet<Entrenador_Pokemon_Movimiento> Entrenador_Pokemon_Movimiento { get; set; }
        public DbSet<Movimiento> Movimientoes { get; set; }
        public DbSet<Movimiento_Pokemon> Movimiento_Pokemon { get; set; }
        public DbSet<Pokemon> Pokemons { get; set; }
        public DbSet<Redes_Sociales_E> Redes_Sociales_E { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
