//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento_Pokemon
    {
        public int Id { get; set; }
        public int Identificador_P { get; set; }
        public string Código_M { get; set; }
    
        public virtual Movimiento Movimiento { get; set; }
        public virtual Pokemon Pokemon { get; set; }
    }
}
