//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public Movimiento()
        {
            this.Entrenador_Pokemon_Movimiento = new HashSet<Entrenador_Pokemon_Movimiento>();
            this.Movimiento_Pokemon = new HashSet<Movimiento_Pokemon>();
        }
    
        public string Código_M { get; set; }
        public string Nombre_M { get; set; }
        public string Descripción { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<Entrenador_Pokemon_Movimiento> Entrenador_Pokemon_Movimiento { get; set; }
        public virtual ICollection<Movimiento_Pokemon> Movimiento_Pokemon { get; set; }
    }
}
