//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        public Pokemon()
        {
            this.Entrenador_Pokemon = new HashSet<Entrenador_Pokemon>();
            this.Entrenador_Pokemon_Movimiento = new HashSet<Entrenador_Pokemon_Movimiento>();
            this.Movimiento_Pokemon = new HashSet<Movimiento_Pokemon>();
        }
    
        public int Identificador_P { get; set; }
        public string Nombre_P { get; set; }
        public string Tipo1 { get; set; }
        public string Tipo2 { get; set; }
        public int Total { get; set; }
        public int Salud { get; set; }
        public int Ataque { get; set; }
        public int Defensa { get; set; }
        public int Ataque_Especial { get; set; }
        public int Defensa_Especial { get; set; }
        public int Velocidad { get; set; }
        public int Generación { get; set; }
        public string Legendario { get; set; }
    
        public virtual ICollection<Entrenador_Pokemon> Entrenador_Pokemon { get; set; }
        public virtual ICollection<Entrenador_Pokemon_Movimiento> Entrenador_Pokemon_Movimiento { get; set; }
        public virtual ICollection<Movimiento_Pokemon> Movimiento_Pokemon { get; set; }
    }
}
