//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Redes_Sociales_E
    {
        public int Id { get; set; }
        public string Red_Social { get; set; }
        public string Nombre_RS { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Identificador_E { get; set; }
    
        public virtual Entrenador Entrenador { get; set; }
    }
}
