//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Clientes = new HashSet<Cliente>();
            this.Entrenadors = new HashSet<Entrenador>();
        }
    
        public string Nombre_Usuario { get; set; }
        public string Contraseña { get; set; }
        public string Rol { get; set; }
    
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual ICollection<Entrenador> Entrenadors { get; set; }
    }
}
